# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!
#import sys
#sys.path.append("../")
from PyQt5 import QtCore, QtGui, QtWidgets
#import gui.icons_rc as icons_rc
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 693)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/PyffLogoNeu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.hboxlayout.addWidget(self.lineEdit)
        self.toolButton_clearFilter = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_clearFilter.setObjectName("toolButton_clearFilter")
        self.hboxlayout.addWidget(self.toolButton_clearFilter)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setShowGrid(False)
        self.tableView.setObjectName("tableView")
        self.vboxlayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/saveas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon3)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon4)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon5)
        self.actionPause.setObjectName("actionPause")
        self.actionGet = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/get.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionGet.setIcon(icon6)
        self.actionGet.setObjectName("actionGet")
        self.actionSendInit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/sendinit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendInit.setIcon(icon7)
        self.actionSendInit.setObjectName("actionSendInit")
        self.actionSendAll = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/sendall.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendAll.setIcon(icon8)
        self.actionSendAll.setObjectName("actionSendAll")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon9)
        self.actionQuit.setObjectName("actionQuit")
        self.actionChangeFeedbackController = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChangeFeedbackController.setIcon(icon10)
        self.actionChangeFeedbackController.setObjectName("actionChangeFeedbackController")
        self.actionClearFilter = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClearFilter.setIcon(icon11)
        self.actionClearFilter.setObjectName("actionClearFilter")
        self.actionSendModified = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/sendmodified.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSendModified.setIcon(icon12)
        self.actionSendModified.setObjectName("actionSendModified")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon13)
        self.actionStop.setObjectName("actionStop")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGet)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionChangeFeedbackController)
        self.toolBar.addAction(self.actionSendInit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pyff"))
        self.label.setText(_translate("MainWindow", "Filter:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "&Open..."))
        self.actionOpen.setStatusTip(_translate("MainWindow", "Open an Existing File"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save &As..."))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionGet.setText(_translate("MainWindow", "Refresh"))
        self.actionGet.setToolTip(_translate("MainWindow", "Refresh varialbes from Feedback"))
        self.actionSendInit.setText(_translate("MainWindow", "SendInit"))
        self.actionSendAll.setText(_translate("MainWindow", "Send All"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionChangeFeedbackController.setText(_translate("MainWindow", "Connect"))
        self.actionClearFilter.setText(_translate("MainWindow", "clearFilter"))
        self.actionSendModified.setText(_translate("MainWindow", "Send Modified"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))


